// Toggle display
export const TOGGLE_BULK_IMPORT_FORM = 'TOGGLE_BULK_IMPORT_FORM';

// Add to Database
export const ADD_BULK_IMPORT = 'ADD_BULK_IMPORT';
export const ADD_DATA_IMPORT = 'ADD_DATA_IMPORT';

export const UPDATE_DATA_IMPORT = 'UPDATE_DATA_IMPORT';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';

export const FETCH_RESOURCES = 'FETCH_RESOURCES';
export const FETCH_RESOURCE = 'FETCH_RESOURCE';

export const CLEAR_RESOURCES = 'CLEAR_RESOURCES';