export const CLEAR_INCENTIVE = 'CLEAR_INCENTIVE';
export const CLEAR_REQUESTS = 'CLEAR_REQUESTS';
export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const SAVE_INCENTIVE = 'SAVE_INCENTIVE';

export const FETCH_REQUEST_TOTAL = 'FETCH_REQUEST_TOTAL';
export const CLEAR_REQUEST_TOTAL = 'CLEAR_REQUEST_TOTAL';