export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE';
export const DELETE_EVENT = 'DELETE_EVENT';
export const FETCH_SCHEDULE_RESOURCE_IDS = 'FETCH_SCHEDULE_RESOURCE_IDS';
export const FETCH_SCHEDULE = 'FETCH_SCHEDULE';
export const VALIDATE_BLOCKS = 'VALIDATE_BLOCKS';

export const SAVE_AVAILABLE_EVENT = 'SAVE_AVAILABLE_EVENT';
export const CLEAR_AVAILABLE_EVENTS = 'CLEAR_AVAILABLE_EVENTS';
export const DELETE_AVAILABLE_EVENT = 'DELETE_AVAILABLE_EVENT';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';